const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    UPDATE_CART_ITEMS: "UPDATE_CART_ITEMS",
    INCREMENT_CART_ITEM: "INCREMENT_CART_ITEM",
    DECREMENT_CART_ITEM: "DECREMENT_CART_ITEM",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
    REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
    ADD_ALL_WISHLIST_ITEM_TO_CART: "ADD_ALL_WISHLIST_ITEM_TO_CART",
    
}

export default ActionTypes;